spring:
  application:
    name: identity-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/lifeos_identity
    username: lifeos
    password: lifeos
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
