package com.lifeos.taskgoal.authorization;

import com.lifeos.taskgoal.goal.Goal;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

/** Trusted resource facts loaded or generated by task-goal-service, never accepted from a client. */
public record GoalAuthorizationResource(
        String resourceType, String resourceId, String tenantId, Map<String, String> attributes) {

    private static final String RESOURCE_TYPE = "goal";
    private static final String OWNER_ACCOUNT_ID = "ownerAccountId";
    private static final String RESOURCE_EXISTS = "resourceExists";
    private static final String MISSING_OWNER_ACCOUNT_ID = "00000000-0000-0000-0000-000000000000";

    public GoalAuthorizationResource {
        if (!RESOURCE_TYPE.equals(resourceType)) {
            throw new IllegalArgumentException("resourceType must be goal");
        }
        if (tenantId == null || tenantId.isBlank()) {
            throw new IllegalArgumentException("tenantId must not be blank");
        }
        attributes = Map.copyOf(Objects.requireNonNull(attributes, "attributes must not be null"));
        if (resourceId == null) {
            if (!attributes.isEmpty()) {
                throw new IllegalArgumentException("collection resources must not contain attributes");
            }
        } else {
            if (resourceId.isBlank()) {
                throw new IllegalArgumentException("resourceId must not be blank when present");
            }
            if (attributes.get(OWNER_ACCOUNT_ID) == null || attributes.get(OWNER_ACCOUNT_ID).isBlank()) {
                throw new IllegalArgumentException("ownerAccountId must not be blank");
            }
            if (!attributes.keySet().equals(Set.of(OWNER_ACCOUNT_ID))
                    && !attributes.keySet().equals(Set.of(OWNER_ACCOUNT_ID, RESOURCE_EXISTS))) {
                throw new IllegalArgumentException("goal resources may contain only ownerAccountId and resourceExists");
            }
            if (attributes.containsKey(RESOURCE_EXISTS)
                    && !("true".equals(attributes.get(RESOURCE_EXISTS))
                    || "false".equals(attributes.get(RESOURCE_EXISTS)))) {
                throw new IllegalArgumentException("resourceExists must be true or false when present");
            }
        }
    }

    /** Creates pre-persistence facts for a newly generated goal. */
    public static GoalAuthorizationResource forNewGoal(UUID goalId, UUID ownerAccountId, String tenantId) {
        return new GoalAuthorizationResource(
                RESOURCE_TYPE,
                Objects.requireNonNull(goalId, "goalId must not be null").toString(),
                tenantId,
                Map.of(OWNER_ACCOUNT_ID, Objects.requireNonNull(ownerAccountId, "ownerAccountId must not be null").toString()));
    }

    /** Creates facts for an existing persisted goal whose object presence was established locally. */
    public static GoalAuthorizationResource forExistingGoal(UUID goalId, UUID ownerAccountId, String tenantId) {
        return new GoalAuthorizationResource(
                RESOURCE_TYPE,
                Objects.requireNonNull(goalId, "goalId must not be null").toString(),
                tenantId,
                Map.of(
                        OWNER_ACCOUNT_ID, Objects.requireNonNull(ownerAccountId, "ownerAccountId must not be null").toString(),
                        RESOURCE_EXISTS, "true"));
    }

    public static GoalAuthorizationResource fromGoal(Goal goal) {
        return forExistingGoal(goal.getId(), goal.getOwnerAccountId(), goal.getTenantId());
    }

    /**
     * Creates a collection resource with tenant scope only. Collection actions are authorized
     * against the validated subject and tenant; an owner fact would falsely turn them into an
     * object-level request.
     */
    public static GoalAuthorizationResource forCollection(String tenantId) {
        return new GoalAuthorizationResource(
                RESOURCE_TYPE,
                null,
                tenantId,
                Map.of());
    }

    /**
     * Provides safe facts for a non-existent or legacy goal so the policy authority is still
     * invoked. The service then denies regardless of an unexpected allow result.
     */
    public static GoalAuthorizationResource forMissingGoal(UUID goalId, String tenantId) {
        return new GoalAuthorizationResource(
                RESOURCE_TYPE,
                Objects.requireNonNull(goalId, "goalId must not be null").toString(),
                tenantId,
                Map.of(OWNER_ACCOUNT_ID, MISSING_OWNER_ACCOUNT_ID, RESOURCE_EXISTS, "false"));
    }
}
